In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("cylindrical without admixture.csv")
df.columns

Index(['F.A WA', 'F.A unit weight', 'WA average coarse',
       'Average Unit weight coarse ', 'Cement', 'Fine Aggregate',
       'Coarse Aggregate', 'Water', 'Slump', 'Strength 7days',
       'Strength 28days', 'Size in mm', 'Cubical = 0/Cylindrical=1'],
      dtype='object')

In [4]:
X = df.drop(['Cement', 'Fine Aggregate',
       'Coarse Aggregate', 'Water','Strength 7days','Cubical = 0/Cylindrical=1'],axis=1)
y = df.drop(['F.A WA', 'F.A unit weight', 'WA average coarse','Average Unit weight coarse ','Cubical = 0/Cylindrical=1','Slump',
       'Strength 28days', 'Size in mm'], axis=1)
X.columns



Index(['F.A WA', 'F.A unit weight', 'WA average coarse',
       'Average Unit weight coarse ', 'Slump', 'Strength 28days',
       'Size in mm'],
      dtype='object')

In [5]:
y.columns

Index(['Cement', 'Fine Aggregate', 'Coarse Aggregate', 'Water',
       'Strength 7days'],
      dtype='object')

In [6]:
print(X.shape, y.shape)

(205, 7) (205, 5)


In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 1)


In [8]:
linear_scaler = StandardScaler()
xtrain_scaled = linear_scaler.fit_transform(xtrain)
xtest_scaled = linear_scaler.transform(xtest)

# Saving StandardScaler 

In [9]:
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestRegressor

In [10]:
regressor = RandomForestRegressor(n_estimators=50, random_state=0, oob_score=True)
regressor.fit(xtrain_scaled,ytrain)

RandomForestRegressor(n_estimators=50, oob_score=True, random_state=0)

In [11]:
predictions = regressor.predict(xtest_scaled)

In [12]:
print(r2_score(ytest, predictions))

0.9710796731699695


In [22]:
from joblib import dump, load
dump(regressor, "RandomForest_model_97%_accuracy")

['RandomForest_model_97%_accuracy']

In [13]:
print(ytest)

     Cement  Fine Aggregate  Coarse Aggregate  Water  Strength 7days
78      380             710              1060    213         2586.00
97      375             725              1055    207         2597.00
151     470             640              1070    231         3433.60
44      350             710              1060    196         2183.00
40      285             825               990    189         2037.25
67      365             715              1060    202         2224.30
98      340             680              1055    204         2673.00
18      260             815              1010    162         1645.75
152     475             660              1070    233         3397.00
62      350             690              1090    190         2176.45
4       260             785              1030    162         1509.45
172     375             715              1055    210         2607.10
197     470             640              1070    235         3455.35
38      290             825       

In [14]:
x_scaled = linear_scaler.transform(X)

In [15]:
predict = regressor.predict(x_scaled)

In [16]:
print(r2_score(y, predict))

0.9877517501810905


In [17]:
print(predict)

[[ 252.9    800.2   1020.1    156.86  1435.844]
 [ 252.4    799.5   1021.2    155.96  1443.026]
 [ 253.2    808.3   1019.6    158.28  1469.608]
 ...
 [ 352.8    698.9   1046.5    206.28  2652.43 ]
 [ 270.     827.5    971.6    176.94  1611.588]
 [ 290.3    821.4    972.7    191.1   1936.649]]


In [18]:
np.savetxt('random_forest_predictions.csv', predict, delimiter=",")

In [19]:
#Taking the importance of the features 
feature_names = X.columns
feature_importances = regressor.feature_importances_

# Now, you can sort the feature importances and print them along with the feature names
sorted_indices = feature_importances.argsort()[::-1]

print("Feature ranking:")
for i, idx in enumerate(sorted_indices):
    print(f"{i+1}. Feature '{feature_names[idx]}': {feature_importances[idx]}")


Feature ranking:
1. Feature 'Strength 28days': 0.9938453955663661
2. Feature 'Slump': 0.0018926675085001936
3. Feature 'F.A unit weight': 0.0013138828748972802
4. Feature 'Average Unit weight coarse ': 0.001075245799030844
5. Feature 'F.A WA': 0.0010377304075784482
6. Feature 'WA average coarse': 0.0007641733645374417
7. Feature 'Size in mm': 7.090447908974919e-05
